### ISSUE TITLE
Variable values does not change

### ISSUE THREAD

**Issue by raheemdawar** [tomcx/tame4#16] opened 2017-12-25 21:04 UTC
``var Plc;
function startClient() {
    Plc =  TAME.WebServiceClient.createClient({
        serviceUrl: 'http://192.168.1.150/TcAdsWebService.dll',
        //configFileUrl: 'http://192.168.1.2/tamex/resources/demo2.tpy',  //Path to the TPY file
        amsNetId: '5.22.187.194.1.1',
        amsPort: '801',       //default
       // useHandles: handles,    //use handles
        alignment: '4',       //default, set it to "4" if you have TC2 and an ARM based PLC device (i.e. CX90xx), to 8 with TC3
        //language: 'ge',       //default, set it to "en" for english names of days and months
        onReady: test    //this function is defined in each example
    });
}
function test()
{
 
    Plc.writeBool({name:"MAIN.Licht_Hobby1", val: true});
}``
I can read the values but when i modify the variable value it shows me no error but does not changes its value.

**Comment by tomcx** [comment] 2017-12-26 14:17
Are you sure that the variable is not assigned anywhere in the PLC? The variable must be "free" and and not be written in any PLC network. Many people simply try to overwrite their input variables but that's not possible.

**Comment by raheemdawar** [comment] 2017-12-26 21:21
There is no problem in the tame library and the plc variable name was also correct.But the problem was on the access permission to these variables.

**Comment by tomcx** [comment] 2018-01-10 20:40
So the problem is solved and I can close the issue?

**Comment by raheemdawar** [comment] 2018-01-14 13:04
Yeah of course thanks for the support

**Closed as completed** 2018-02-03 14:47 UTC
